/*!
 * 对提交参数一层封装，当POST JSON，并且结果也为JSON时使用 */
exports.postJSON = function (data) {
    return {
        dataType: 'json',
        method: 'POST',
        data: JSON.stringify(data),
        headers: {
            'Content-Type': 'application/json'
        }
    };
};

exports.wx_emotion = [
    { txt: "/::)", zh: "[微笑]", url: "http://cache.soso.com/img/img/e100.gif" },
    { txt: "/::~", zh: "[撇嘴]", url: "http://cache.soso.com/img/img/e101.gif" },
    { txt: "/::B", zh: "[色]", url: "http://cache.soso.com/img/img/e102.gif" },
    { txt: "/::|", zh: "[发呆]", url: "http://cache.soso.com/img/img/e103.gif" },
    { txt: "/:8-)", zh: "[得意]", url: "http://cache.soso.com/img/img/e104.gif" },
    { txt: "/::<", zh: "[流泪]", url: "http://cache.soso.com/img/img/e105.gif" },
    { txt: "/::$", zh: "[害羞]", url: "http://cache.soso.com/img/img/e106.gif" },
    { txt: "/::X", zh: "[闭嘴]", url: "http://cache.soso.com/img/img/e107.gif" },
    { txt: "/::Z", zh: "[睡]", url: "http://cache.soso.com/img/img/e108.gif" },
    { txt: "/::'(", zh: "[大哭]", url: "http://cache.soso.com/img/img/e109.gif" },
    { txt: "/::-|", zh: "[尴尬]", url: "http://cache.soso.com/img/img/e110.gif" },
    { txt: "/::@", zh: "[发怒]", url: "http://cache.soso.com/img/img/e111.gif" },
    { txt: "/::P", zh: "[调皮]", url: "http://cache.soso.com/img/img/e112.gif" },
    { txt: "/::D", zh: "[呲牙]", url: "http://cache.soso.com/img/img/e113.gif" },
    { txt: "/::O", zh: "[惊讶]", url: "http://cache.soso.com/img/img/e114.gif" },
    { txt: "/::(", zh: "[难过]", url: "http://cache.soso.com/img/img/e115.gif" },
    { txt: "/::+", zh: "[酷]", url: "http://cache.soso.com/img/img/e116.gif" },
    { txt: "/:--b", zh: "[冷汗]", url: "http://cache.soso.com/img/img/e117.gif" },
    { txt: "/::Q", zh: "[抓狂]", url: "http://cache.soso.com/img/img/e118.gif" },
    { txt: "/::T", zh: "[吐]", url: "http://cache.soso.com/img/img/e119.gif" },
    { txt: "/:,@P", zh: "[偷笑]", url: "http://cache.soso.com/img/img/e120.gif" },
    { txt: "/:,@-D", zh: "[可爱]", url: "http://cache.soso.com/img/img/e121.gif" },
    { txt: "/::d", zh: "[白眼]", url: "http://cache.soso.com/img/img/e122.gif" },
    { txt: "/:,@o", zh: "[傲慢]", url: "http://cache.soso.com/img/img/e123.gif" },
    { txt: "/::g", zh: "[饥饿]", url: "http://cache.soso.com/img/img/e124.gif" },
    { txt: "/:|-)", zh: "[困]", url: "http://cache.soso.com/img/img/e125.gif" },
    { txt: "/::!", zh: "[惊恐]", url: "http://cache.soso.com/img/img/e126.gif" },
    { txt: "/::L", zh: "[流汗]", url: "http://cache.soso.com/img/img/e127.gif" },
    { txt: "/::>", zh: "[憨笑]", url: "http://cache.soso.com/img/img/e128.gif" },
    { txt: "/::,@", zh: "[大兵]", url: "http://cache.soso.com/img/img/e129.gif" },
    { txt: "/:,@f", zh: "[奋斗]", url: "http://cache.soso.com/img/img/e130.gif" },
    { txt: "/::-S", zh: "[咒骂]", url: "http://cache.soso.com/img/img/e131.gif" },
    { txt: "/:?", zh: "[疑问]", url: "http://cache.soso.com/img/img/e132.gif" },
    { txt: "/:,@x", zh: "[嘘]", url: "http://cache.soso.com/img/img/e133.gif" },
    { txt: "/:,@@", zh: "[晕]", url: "http://cache.soso.com/img/img/e134.gif" },
    { txt: "/::8", zh: "[折磨]", url: "http://cache.soso.com/img/img/e135.gif" },
    { txt: "/:,@!", zh: "[衰]", url: "http://cache.soso.com/img/img/e136.gif" },
    { txt: "/:!!!", zh: "[骷髅]", url: "http://cache.soso.com/img/img/e137.gif" },
    { txt: "/:xx", zh: "[敲打]", url: "http://cache.soso.com/img/img/e138.gif" },
    { txt: "/:bye", zh: "[再见]", url: "http://cache.soso.com/img/img/e139.gif" },
    { txt: "/:wipe", zh: "[擦汗]", url: "http://cache.soso.com/img/img/e140.gif" },
    { txt: "/:dig", zh: "[抠鼻]", url: "http://cache.soso.com/img/img/e141.gif" },
    { txt: "/:handclap", zh: "[鼓掌]", url: "http://cache.soso.com/img/img/e142.gif" },
    { txt: "/:&-(", zh: "[糗大了]", url: "http://cache.soso.com/img/img/e143.gif" },
    { txt: "/:B-)", zh: "[坏笑]", url: "http://cache.soso.com/img/img/e144.gif" },
    { txt: "/:<@", zh: "[左哼哼]", url: "http://cache.soso.com/img/img/e145.gif" },
    { txt: "/:@>", zh: "[右哼哼]", url: "http://cache.soso.com/img/img/e146.gif" },
    { txt: "/::-O", zh: "[哈欠]", url: "http://cache.soso.com/img/img/e147.gif" },
    { txt: "/:>-|", zh: "[鄙视]", url: "http://cache.soso.com/img/img/e148.gif" },
    { txt: "/:P-(", zh: "[委屈]", url: "http://cache.soso.com/img/img/e149.gif" },
    { txt: "/::'|", zh: "[快哭了]", url: "http://cache.soso.com/img/img/e150.gif" },
    { txt: "/:X-)", zh: "[阴险]", url: "http://cache.soso.com/img/img/e151.gif" },
    { txt: "/::*", zh: "[亲亲]", url: "http://cache.soso.com/img/img/e152.gif" },
    { txt: "/:@x", zh: "[吓]", url: "http://cache.soso.com/img/img/e153.gif" },
    { txt: "/:8*", zh: "[可怜]", url: "http://cache.soso.com/img/img/e154.gif" },
    { txt: "/:pd", zh: "[菜刀]", url: "http://cache.soso.com/img/img/e155.gif" },
    { txt: "/:<W>", zh: "[西瓜]", url: "http://cache.soso.com/img/img/e156.gif" },
    { txt: "/:beer", zh: "[啤酒]", url: "http://cache.soso.com/img/img/e157.gif" },
    { txt: "/:basketb", zh: "[篮球]", url: "http://cache.soso.com/img/img/e158.gif" },
    { txt: "/:oo", zh: "[乒乓]", url: "http://cache.soso.com/img/img/e159.gif" },
    { txt: "/:coffee", zh: "[咖啡]", url: "http://cache.soso.com/img/img/e160.gif" },
    { txt: "/:eat", zh: "[饭]", url: "http://cache.soso.com/img/img/e161.gif" },
    { txt: "/:pig", zh: "[猪头]", url: "http://cache.soso.com/img/img/e162.gif" },
    { txt: "/:rose", zh: "[玫瑰]", url: "http://cache.soso.com/img/img/e163.gif" },
    { txt: "/:fade", zh: "[凋谢]", url: "http://cache.soso.com/img/img/e164.gif" },
    { txt: "/:showlove", zh: "[嘴唇]", url: "http://cache.soso.com/img/img/e165.gif" },
    { txt: "/:heart", zh: "[爱心]", url: "http://cache.soso.com/img/img/e166.gif" },
    { txt: "/:break", zh: "[心碎]", url: "http://cache.soso.com/img/img/e167.gif" },
    { txt: "/:cake", zh: "[蛋糕]", url: "http://cache.soso.com/img/img/e168.gif" },
    { txt: "/:li", zh: "[闪电]", url: "http://cache.soso.com/img/img/e169.gif" },
    { txt: "/:bome", zh: "[炸弹]", url: "http://cache.soso.com/img/img/e170.gif" },
    { txt: "/:kn", zh: "[刀]", url: "http://cache.soso.com/img/img/e171.gif" },
    { txt: "/:footb", zh: "[足球]", url: "http://cache.soso.com/img/img/e172.gif" },
    { txt: "/:ladybug", zh: "[瓢虫]", url: "http://cache.soso.com/img/img/e173.gif" },
    { txt: "/:shit", zh: "[便便]", url: "http://cache.soso.com/img/img/e174.gif" },
    { txt: "/:moon", zh: "[月亮]", url: "http://cache.soso.com/img/img/e175.gif" },
    { txt: "/:sun", zh: "[太阳]", url: "http://cache.soso.com/img/img/e176.gif" },
    { txt: "/:gift", zh: "[礼物]", url: "http://cache.soso.com/img/img/e177.gif" },
    { txt: "/:hug", zh: "[拥抱]", url: "http://cache.soso.com/img/img/e178.gif" },
    { txt: "/:strong", zh: "[强]", url: "http://cache.soso.com/img/img/e179.gif" },
    { txt: "/:weak", zh: "[弱]", url: "http://cache.soso.com/img/img/e180.gif" },
    { txt: "/:share", zh: "[握手]", url: "http://cache.soso.com/img/img/e181.gif" },
    { txt: "/:v", zh: "[胜利]", url: "http://cache.soso.com/img/img/e182.gif" },
    { txt: "/:@)", zh: "[抱拳]", url: "http://cache.soso.com/img/img/e183.gif" },
    { txt: "/:jj", zh: "[勾引]", url: "http://cache.soso.com/img/img/e184.gif" },
    { txt: "/:@@", zh: "[拳头]", url: "http://cache.soso.com/img/img/e185.gif" },
    { txt: "/:bad", zh: "[差劲]", url: "http://cache.soso.com/img/img/e186.gif" },
    { txt: "/:lvu", zh: "[爱你]", url: "http://cache.soso.com/img/img/e187.gif" },
    { txt: "/:no", zh: "[NO]", url: "http://cache.soso.com/img/img/e188.gif" },
    { txt: "/:ok", zh: "[OK]", url: "http://cache.soso.com/img/img/e189.gif" },
    { txt: "/:love", zh: "[爱情]", url: "http://cache.soso.com/img/img/e190.gif" },
    { txt: "/:<L>", zh: "[飞吻]", url: "http://cache.soso.com/img/img/e191.gif" },
    { txt: "/:jump", zh: "[跳跳]", url: "http://cache.soso.com/img/img/e192.gif" },
    { txt: "/:shake", zh: "[发抖]", url: "http://cache.soso.com/img/img/e193.gif" },
    { txt: "/:<O>", zh: "[怄火]", url: "http://cache.soso.com/img/img/e194.gif" },
    { txt: "/:circle", zh: "[转圈]", url: "http://cache.soso.com/img/img/e195.gif" },
    { txt: "/:kotow", zh: "[磕头]", url: "http://cache.soso.com/img/img/e196.gif" },
    { txt: "/:turn", zh: "[回头]", url: "http://cache.soso.com/img/img/e197.gif" },
    { txt: "/:skip", zh: "[跳绳]", url: "http://cache.soso.com/img/img/e198.gif" },
    { txt: "/:oY", zh: "[挥手]", url: "http://cache.soso.com/img/img/e199.gif" },
    { txt: "/:#-0", zh: "[激动]", url: "http://cache.soso.com/img/img/e200.gif" },
    { txt: "/:hiphot", zh: "[街舞]", url: "http://cache.soso.com/img/img/e201.gif" },
    { txt: "/:kiss", zh: "[献吻]", url: "http://cache.soso.com/img/img/e202.gif" },
    { txt: "/:<&", zh: "[左太极]", url: "http://cache.soso.com/img/img/e203.gif" },
    { txt: "/:&>", zh: "[右太极]", url: "http://cache.soso.com/img/img/e204.gif" },
];
